version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch:
        update-types: [patch]
      minor:
        update-types: [minor]
    open-pull-requests-limit: 20
