version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - pocketbase
    networks:
      - app-network

  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    ports:
      - 8090:8080
    volumes:
      - pb:/pb/pb_data
    networks:
      - app-network

volumes:
  pb:

networks:
  app-network:
    driver: bridge 