'use client';

// import { Inter } from "next/font/google";
// import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { Metadata } from 'next';
import Link from 'next/link';
import { Suspense } from 'react';
import { Container, Nav, Navbar } from 'react-bootstrap';
import SSRProvider from 'react-bootstrap/SSRProvider';

const queryClient = new QueryClient();

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <QueryClientProvider client={queryClient}>
          <Navbar>
            <Container>
              <Navbar.Brand>
                <Link href='/'>Home</Link>
              </Navbar.Brand>
              <Navbar.Collapse className='gap-3'>
                <Nav.Link as='div'>
                  <Link href='/inspections'>Inspections crud</Link>
                </Nav.Link>

                <Nav.Link as='div'>
                  <Link href='/inspection-wizard/new'>Inspection wizard</Link>
                </Nav.Link>
              </Navbar.Collapse>
            </Container>
          </Navbar>

          <Container>{children}</Container>
        </QueryClientProvider>
      </body>
    </html>
  );
}
